"""Generate LaTeX table fragments from curated paper-table CSVs."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PAPER_TABLES = ROOT / "experiments" / "results" / "paper_tables"
OUT_DIR = ROOT / "paper" / "tables"


TABLES = {
    "table_2_r5_wnut17": "WNUT17 diagnostic and viability checks.",
    "table_3_event_training_signal": "Event-training movement in controlled and field-style probes.",
    "table_4_diagnostic_ranking": "R6a diagnostic ranking and uncertainty boundary.",
    "table_6_public_conll2000": "CoNLL2000 public BIO/chunking multiseed case study.",
    "table_7_public_uncertainty": "CoNLL2000 public uncertainty boundary.",
    "table_8_b7_constrained_product": "B7 constrained-product decoding baseline.",
    "table_9_r7_sensitivity": "R7 lambda/rule sensitivity and boundary cases.",
}


def escape_latex(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def column_spec(n_cols: int) -> str:
    return "l" * n_cols


def write_table(name: str, caption: str) -> None:
    rows_path = PAPER_TABLES / f"{name}.csv"
    rows: list[dict[str, str]]
    with rows_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        fields = reader.fieldnames or []
    if not fields:
        raise ValueError(f"no columns in {rows_path}")

    label = name.replace("_", ":")
    lines = [
        "% Generated by scripts/analysis/generate_latex_tables.py.",
        "% Do not edit numeric values by hand; edit curated CSVs and regenerate.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        rf"\caption{{{escape_latex(caption)}}}",
        rf"\label{{tab:{label}}}",
        rf"\begin{{tabular}}{{{column_spec(len(fields))}}}",
        r"\toprule",
        " & ".join(escape_latex(field) for field in fields) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(escape_latex(row[field]) for field in fields) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    (OUT_DIR / f"{name}.tex").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, caption in TABLES.items():
        write_table(name, caption)
        print(f"WROTE {OUT_DIR / (name + '.tex')}")


if __name__ == "__main__":
    main()
